### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by AKBIROCK3** [Gyoonus/deoptfuscator#1]
hi could you please tell me what's wrong
i got that message

Traceback (most recent call last):
  File "deoptfuscator.py", line 18, in <module>
    deobfuscator.main(".apk/"+dex)
  File "deobfuscator\deobfuscator.py", line 9, in main
    ret = opaque_id.opaque_id(dex)
  File "deobfuscator\opaque_id.py", line 6, in opaque_id
    child = subprocess.Popen([os.getenv('ANDROID_HOST_OUT')+'/bin/OTest'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

what's wrong i tried by both python2 And python3 but the same error

**Comment by Gyoonus** [comment]
This tools always set environment before running tool like using below command.

$. ./launch.sh
Or
$source ./launch.sh

**Comment by AKBIROCK3** [comment]
> This tools always set environment before running tool like using below command.
> 
> $. ./launch.sh
> Or
> $source ./launch.sh

hi thnx for your reply when i used those commands ./launch.sh and source ./launch.sh
nothing happened 
![Capture](https://user-images.githubusercontent.com/58403612/83974516-b2dc9880-a8e5-11ea-8800-57b6b2a485f1.PNG)

what should i do

**Comment by Gyoonus** [comment]
After then 
Run our code
$ python3 deoptfuscator.py <obfuscated_apk>

Our tool is based on ubuntu linux system.
It is not run on the windows OS.

**Comment by AKBIROCK3** [comment]
> After then
> Run our code
> $ python3 deoptfuscator.py <obfuscated_apk>
> 
> Our tool is based on ubuntu linux system.
> It is not run on the windows OS.

well im using windows so that's the reason 
you're not planning to add support for windows ?

**Comment by Gyoonus** [comment]
Sorry, our tool is based on android art compiler which can be run on linux. So we are not considering windows OS🤣.
