### ISSUE TITLE
Error - File "deoptfuscator.py", line 18, in <module>...

### ISSUE THREAD

**Issue by min3rv4** [Gyoonus/deoptfuscator#10]
Machine built precisely to version and following steps.

![image](https://user-images.githubusercontent.com/59661336/156824118-9f1c6dec-9f38-40ea-be9a-6a4ccd93556f.png)

Environmental variables set with launch.sh and then running against APK file in same directory.

![image](https://user-images.githubusercontent.com/59661336/156824301-4299a9cb-4e1a-403f-ab38-cc99d014063b.png)

Attempted to run against a directory with the APK unzipped as well and did not work.

Install steps were as follows:
    
    sudo apt-get install -y libboost-all-dev  
    sudo apt-get install -y libjsoncpp-dev
    sudo apt-get install -y openjdk-11-jdk
    sudo dpkg --add-architecture i386  
    sudo apt-get update  
    sudo apt-get install -y libc6:i386 libstdc++6:i386
    sudo apt-get install -y zipalign
    sudo apt-get install -y apksigner
    
    sudo apt install -y curl
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    sudo apt install -y git-lfs
    git clone https://github.com/Gyoonus/deoptfuscator.git

All installed without error message.  Have tried running with sudo and get same error.
Have tried running with working directory in command, receive same error.

![image](https://user-images.githubusercontent.com/59661336/156824734-8ddeef92-0e9c-4859-abb5-5df11e4653a9.png)

Please advise.  Thanks!

**Comment by Gyoonus** [comment]
I think java env is not set in yours.
Why don't you check your jav env in your machine
