### ISSUE TITLE
Doesn't work for magicPH dexpro obfuscated applications

### ISSUE THREAD

**Issue by devguru-udus** [Gyoonus/deoptfuscator#2]
is there a way to deobfuscate android application that are obfuscated with magicPH dexpro android application?

**Comment by Gyoonus** [comment]
If you send me about that information (ex.app), we consider it!!

**Comment by devguru-udus** [comment]
i don't know where to find the ex.app of a thing, why not just obfuscate a android app with magicPH dexpro android application, then try to deofuscate it and see if it will work

**Comment by devguru-udus** [comment]
> If you send me about that information (ex.app), we consider it!!

i don't know where to find the ex.app of a thing, why not just obfuscate a android app with magicPH dexpro android application, then try to deofuscate it and see if it will work

**Comment by Gyoonus** [comment]
Plz send us app which adjusting dexpro.
We don't know about dexpro.
And if you can, plz send about dexpro's information.

**Comment by devguru-udus** [comment]
Since dexpro or dexprotector decrypt at runtime, is it possible to extract
the original file at runtime?

**Comment by devguru-udus** [comment]
OK, I'll send you the dexpro app

**Comment by devguru-udus** [comment]
Download dexpro from this link:

https://m.apkpure.com/dexprotector-for-android/mph.trunksku.apps.dexpro/amp

Use the app to obfuscate any apk you have with you, then try to deobfuscate
and see if it will work

**Comment by devguru-udus** [comment]
To know more about dexprotector, go to: https://dexprotector.com/

**Comment by Gyoonus** [comment]
Our tool's target is not for dynamic loader. You can get dexprotector's original dex using memory dump technique.
