### ISSUE TITLE
Error: Unable to access jarfile /apktool.jar

### ISSUE THREAD

**Issue by rahul-sani** [Gyoonus/deoptfuscator#5]
Error: Unable to access jarfile /apktool.jar
Traceback (most recent call last):
  File "deoptfuscator.py", line 18, in <module>
    dex_li = [a for a in os.listdir(".apk") if a.endswith(".dex") and a.startswith("classes")]
FileNotFoundError: [Errno 2] No such file or directory: '.apk'

command used: python3 deoptfuscator.py apkname.apk

**Comment by geunhayou66** [comment]
You should use below command before using our tool

$. ./launch.sh
or
$ source launch.sh

These commands set environment variables.

If another problem occurs, please create a new issue.
