### ISSUE TITLE
KeyError: 1765

### ISSUE THREAD

**Issue by rahul-sani** [Gyoonus/deoptfuscator#6]
location : True
.apk/classes.dex
Traceback (most recent call last):
  File "deoptfuscator.py", line 23, in <module>
    deobfuscator.main(".apk/"+dex)
  File "deobfuscator/deobfuscator.py", line 20, in main
    dexfile(dex)
  File "deobfuscator/classes.py", line 27, in dexfile
    dexf_a[dex_location+2] = class_dic[f_idx+add]
KeyError: 1765

**Comment by rahul-sani** [comment]
used the following commands: 
```
source launch.sh
python3 deoptfuscator.py <apkname>
```

**Comment by Gyoonus** [comment]
used this command 
python3 deoptfuscator.py <apk_path>
If it throwed error, please upload your sample apk on this Issue!

**Comment by rahul-sani** [comment]
https://play.google.com/store/apps/details?id=com.sbi.lotusintouch

**Comment by Gyoonus** [comment]
I solved the error about the app you sent.
The app is not highly obfuscated, so it may not be de-obfuscated in deoptfuscator.
We will develop a setting for de-obfuscation intensity level

**Comment by rahul-sani** [comment]
Cool. All the best
