### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by MrPooyaX** [Gyoonus/deoptfuscator#7]
location : True
.apk/classes.dex
Traceback (most recent call last):
  File "deoptfuscator.py", line 24, in <module>
    deobfuscator.main(".apk/"+dex)
  File "deobfuscator/deobfuscator.py", line 20, in main
    dexfile(dex)
  File "deobfuscator/classes.py", line 20, in dexfile
    class_dic[int(num[0])] = int(num[1])
ValueError: invalid literal for int() with base 10: '45b8'

**Comment by MrPooyaX** [comment]
i edited line 20 of 'classes.py' and that error solved:
try:
    class_dic[int(num[0])] = int(num[1])
except ValueError:
    class_dic[int(num[0], 16)] = int(num[1])

output apk not fully and correctly deobfuscated
please check yourself and try to deobfuscate:
http://likeg.ir/tel.apk

**Comment by Gyoonus** [comment]
Thank you! We eagar to solved it.

**Comment by geunhayou66** [comment]
First of all, thank you for correcting the error.
If you look at the below control flow graph, it becomes de-obfuscated.
However, if there is a protection solution in .so files, it may not be possible to execute the app.
Does it matter if the app can run or not?

![제목 없음](https://user-images.githubusercontent.com/64211521/107163898-82f31100-69ef-11eb-9f69-600ed7f15b09.png)
